ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('adminal/', admin.site.urls),
    path('', include('shop.urls'), name='shop')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name='store'
urlpatterns=[
	path('keranjang', cart, name='cart'),
	path('bayar', checkout, name='checkout'),
	path('update_item/', updateItem, name='update_item'),

	path('process_order/', processOrder, name='processOrder'),	
	path('', PerempuanListView.as_view(), name='home'),
	path('detail/<int:slug>', ProductDetailView.as_view(), name='detail'),
	path('store/<page>', PerempuanListView.as_view(), name='perempuan'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.	

class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.name

class Category(models.Model):
	name = models.CharField(max_length=255, null=True)

	def __str__(self):
		return self.name
		

class Product(models.Model):
	slug = models.SlugField(blank=True, editable=False)
	published = models.DateTimeField(auto_now=True)
	name = models.CharField(max_length=200, null=True)
	kategori = models.CharField(max_length=200, null=True)
	price = models.DecimalField(max_digits=9, decimal_places=3)
	digital = models.BooleanField(default=False, null=True, blank=True)
	image = models.ImageField(null=True, blank=True)
	image2 = models.ImageField(null=True, blank=True)

	def __str__(self):
		return self.name

	def save(self):
		self.slug = slugify(self.id)
		super().save()

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url
	@property
	def image2URL(self):
		try:
			url = self.image2.url
		except:
			url = ''
		return url


class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False, null=True, blank=False)
	transaction_id = models.CharField(max_length=200, null=True)

	def __str__(self):
		return str(self.id)

	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping
	

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total
	


class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.product.price * self.quantity
		return total
	


class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
	address = models.CharField(max_length=200, null=True, blank=False)
	city = models.CharField(max_length=200, null=True, blank=False)
	state = models.CharField(max_length=200, null=True, blank=False)
	zipcode = models.CharField(max_length=200, null=True, blank=False)
	bank = models.CharField(max_length=200, null=True, blank=False)
	nomor = models.CharField(max_length=200, null=True, blank=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address
	



class Men(models.Model):
	name = models.CharField(max_length=200, null=True)
	price = models.FloatField()
	digital = models.BooleanField(default=False, null=True, blank=True)
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

shop/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
import json
import datetime
from . utils import *

from .models import *
# Create your views here.
def store(request):

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items
	else:
		items = []
		order = {'get_cart_items_total':0, 'get_cart_item':0, 'shipping':False}
		cartItems = order['get_cart_items']

	products = Product.objects.all()
	ordering=['-published']
	context = {
	'products':products,
	'cartItems':cartItems,
	}
	return render(request, 'shop/store.html', context)

class ProductDetailView(DetailView):
    model = Product
    template_name = "shop/product_detail.html"
    context_object_name= "product"


class PerempuanListView(ListView):
    model = Product
    template_name = "shop/store.html"
    context_object_name= "products"
    ordering = ['-published']
    paginate_by = 8

def cart(request):
	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	context = {
	'items':items,
	'order':order,
	'cartItems':cartItems,
	}
	return render(request, 'shop/cart.html', context)

def checkout(request):

	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']
		
	context = {
	'items':items,
	'order':order,
	'cartItems':cartItems,
	}
	return render(request, 'shop/checkout.html', context)

def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']

	print ('Action:', action)
	print ('productId:', productId)

	customer = request.user.customer
	product = Product.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()
	return JsonResponse('Item was added', safe=False)

def processOrder(request):
	transaction_id = datetime.datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)

	else:
		customer, order = guestOrder(request, data)


	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if total == order.get_cart_total:
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
			customer=customer,
			order=order,
			address=data['shipping']['address'],
			city=data['shipping']['city'],
			state=data['shipping']['state'],
			zipcode=data['shipping']['zipcode'],
			)

	return JsonResponse('Payment complete', safe=False)

shop/templates/shop/cart.html
{% extends "shop/main.html" %}
{% load static %}
{% block page_title %}
	Keranjang
{% endblock page_title %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a class="btn btn-outline-dark" href="{% url 'store:home' %}">&#x2190;Lanjutkan Belanja</a>
				<br><br>

				<table class="table">
					<tr>
						<th><h5>Jumlah: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total: <strong>Rp. {{order.get_cart_total|floatformat:3}}</strong></h5></th>
						<th><a  style="float:right; margin:5px" class="btn btn-success" href="{% url 'store:checkout' %}">Bayar</a></th>
					</tr>
				</table>
			</div>
			<br>

			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Barang</strong></div>
					<div style="flex:1"><strong>Harga</strong></div>
					<div style="flex:1"><strong>Jumlah</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
					
				
				<div class="cart-row">
					<div style="flex:2">
							<img class="row-image" src="{{item.product.imageURL}}">
						
					</div>
					<div style="flex:2">{{item.product.name}}</div>
					<div style="flex:1">Rp. {{item.product.price|floatformat:3}}</div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static "images/arrow-up.png" %}">
							<img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static "images/arrow-down.png" %}">
						</div>
					</div>
					<div style="flex:1">Rp. {{item.get_total|floatformat:3}}</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

shop/templates/shop/checkout.html
{% extends "shop/main.html" %}
{% load static %}
{% block page_title %}
	Pembayaran
{% endblock page_title %}
{% block content %}
	<div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					{%csrf_token%}
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Nama..">
						</div>
					
							<div class="form-field">
							<input required class="form-control" type="text" name="email" placeholder="Email..">
						</div>
					</div>
					<div id="shipping-info">
						<hr>
						<p>Alamat Penerima:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Alamat">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="Kota">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="Provinsi">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Kode Pos">
						</div>
					</div>
					<hr>
					<button id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
						Lanjutkan
					</button>
				</form>
			</div>
			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Pembayaran</small><br>
				
				<hr>
				<button id="make-payment" class="btn btn-success btn-block"	>Bayar</button>
			</div>
		
		</div>
		<div class="col-lg-6">
			<div class="box-element">
				<a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190;Kembali ke Keranjang</a>
				<hr>
				<h3>Daftar Barang</h3>
				<hr>
				
				{% for item in items %}	
				<div class="cart-row">
					<div style="flex:2">
						<img class="row-image" src="{{item.product.imageURL}}">
					</div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Rp. {{item.product.price|floatformat:3}}</p></div>
					<div style="flex:1"><p>X {{item.quantity}}</p></div>	
				</div>
				{% endfor %}

				<h5>Jumlah: {{order.get_cart_items}}</h5>
				<h5>Total: Rp. {{order.get_cart_total|floatformat:3}}</h5>
			</div>
		</div>
	</div>

<script type="text/javascript">
	var shipping = '{{oder.shipping}}';
	var total = '{{order.get_cart_total}}'

	if(shipping == 'False'){
		document.getElementById('shipping-info').innerHTML = ''	
	}

	if (user != 'AnonymousUser'){
	  document.getElementById('user-info').innerHTML = ''
	}

	if (shipping == 'False' && user !='AnonymousUser'){
	  document.getElementById('form-wrapper').classList.add("hidden");
	  document.getElementById('payment-info').classList.remove("hidden");

	}

	var form = document.getElementById('form');
	csrftoken = form.getElementsByTagName("input")[0].value
	console.log('token:', form.getElementsByTagName('input')[0].value)

	form.addEventListener('submit', function(e){
		e.preventDefault()
		console.log('Form terkirim')
		document.getElementById('form-button').classList.add('hidden')
		document.getElementById('payment-info').classList.remove('hidden')
	});

	document.getElementById('make-payment').addEventListener('click', function(e){
		submitFormData()
	})

	function submitFormData(){
		console.log('Bayar sukses')
		var userFormData = {
			'name':null,
			'email':null,
			'total':total,
		}
		var shippingInfo = {
			'address':null,
			'city':null,
			'state':null,
			'zipcode':null,
		}
		if(shipping != 'False'){
			shippingInfo.address = form.address.value
			shippingInfo.city = form.city.value
			shippingInfo.state = form.state.value
			shippingInfo.zipcode = form.zipcode.value
		}

		if(user == 'AnonymousUser'){
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}

		var url= '/process_order/'
		fetch(url,{
			method:'POST',
			headers:{
				'Content-Type':'application/json',
				'X-CSRFToken':csrftoken,
			},
			body:JSON.stringify({'form':userFormData,'shipping':shippingInfo})
		})
		.then((response) => response.json())
		.then((data)=> {
			console.log('Sucess:',data);
			alert('Pembayaran berhasil');

			cart = {}
		document.cookie = 'cart=' + JSON.stringify(cart) +";domain=;path=/"
			window.location.href ="{%url 'store:perempuan' 1%}"
		
		})

	}
</script>
{% endblock content %}

shop/templates/shop/kategori.html
{% extends "shop/main.html" %}
{% load static %}
{% block page_title %}
	Perempuan
{% endblock page_title %}
{% block content %}

<h2>Baju Perempuan</h2><br><br>
	<div class="row">
		{% for product in products  %}
			<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 px-1">
				{% if product.image %}
					<img class="img-fluid" src="{{product.imageURL}}">
				{% endif %}
				<div class="box-element product">
					<h5>{{product.name}}</h5>
					<h6 style="display:inline-block;">Rp. {{product.price|floatformat:3}}</h6>
					<hr>
					<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">+ Keranjang</button>
					<a class="btn btn-outline-success" href="{% url 'store:detail' product.slug %}">Lihat</a>
				</div>
				<br>
				
			</div>
		{% endfor %}
	</div>
	
{% if is_paginated %}
<nav aria-label="storelist">
	<ul class="pagination">	
		{% if page_obj.has_previous %}
			<li class="page-item">
		    	<a class="page-link" href="{% url 'store:kategori' kategori page_obj.previous_page_number %}">Sebelumnya</a>
			</li>
		{% else %}
			<li class="page-item disabled">
	    		<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Sebelumnya</a>
		{% endif %}

		 {% for page in paginator.page_range %}

		    	{% if page is page_obj.number %}
		    	
		    	 <li class="page-item active" aria-current="page">
		    	 	<span class="page-link" href="#">{{page}} <span class="sr-only">(current)</span></span>
		    	 </li>	
		    	
		    	{% else %}
		    	 <li class="page-item">
		    	 	<a class="page-link" href="{% url 'store:kategori' kategori page%}">{{page}} </a>
		    	 </li>
		    	{% endif %}
		    {% endfor %}

		{% if page_obj.has_next %}
			<li class="page-item">
		    	<a class="page-link" href="{% url 'store:kategori' kategori page_obj.next_page_number %}">Berikutnya</a>
			</li>
		{% else %}
			<li class="page-item disabled">
	    		<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Berikutnya</a>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock content %}

shop/templates/shop/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>
  {% block page_title %}
  
  {% endblock page_title %}
  </title>
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
 
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  
  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name){
    var cookieValue = null;
    if (document.cookie && document.cookie !== ''){
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++){
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length +1) === (name + '=')){
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getToken('csrftoken');

  function getCookie(name){
    var cookieArr=document.cookie.split(";");

    for(var i = 0; i < cookieArr.length; i++){
      var cookiePair = cookieArr[i].split("=");

      if(name == cookiePair[0].trim()){
        return decodeURIComponent(cookiePair[1]);
      }
    }
    return null;
  }
  var cart=JSON.parse(getCookie('cart'));
  if(cart == undefined){
    cart = {}
    console.log('cart was created')
    document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
  }

  console.log('cart:',cart);
  </script>
</head>

<body>
 
  
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
   <div class="container">
    <a class="navbar-brand" href="{% url 'store:perempuan' 1%}">ASTARAYA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    
  
      </li>
    </ul>
  <div class="form-inline my-2 my-lg-0">
    <a href="{% url 'store:cart' %}"><img src="{% static "images/cart.png" %}" id="cart-icon"></a>
    
    
  </div>
  </div>
</div>
</nav>
<br>
  {% block banner %}

  {% endblock banner %}

<div class="container">
  {% block content %}
      
  {% endblock content %}
</div>
<br><br><br>

<script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
<script type="text/javascript"src="{% static "js/bootstrap.min.js" %}"></script> 
<script type="text/javascript" src="{% static "js/cart.js" %}"></script>
</body>
</html>

shop/templates/shop/main2.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>
      
  </title>
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
  
  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name){
    var cookieValue = null;
    if (document.cookie && document.cookie !== ''){
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++){
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length +1) === (name + '=')){
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getToken('csrftoken');
  </script>
</head>

<body>
 
  
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
   <div class="container">
    <a class="navbar-brand" href="{% url 'store:home' %}">ASTARAYA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'store:perempuan' 1 %}">Perempuan</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'store:men' %}">Laki-laki</a>
      </li>
    </ul>
  <div class="form-inline my-2 my-lg-0">
    <a href="#" class="btn btn-warning">Login</a>
    <a href="{% url 'store:cart' %}"><img src="{% static "images/cart.png" %}" id="cart-icon"></a>
    <p id="cart-total">{{cartItems}}</p>
  </div>
  </div>
</div>
</nav>
<br>
<div class="jumbotron">
  {% block banner %}

  {% endblock banner %}
</div>
<div class="container">
  {% block content %}
      
  {% endblock content %}
</div>


<script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
<script type="text/javascript"src="{% static "js/bootstrap.min.js" %}"></script> 
<script type="text/javascript" src="{% static "js/cart.js" %}"></script>
</body>
</html>

shop/templates/shop/men.html
{% extends "shop/main.html" %}
{% load static %}
{% block page_title %}
	Laki-Laki
{% endblock page_title %}
{% block content %}
	<div class="row">
		{% for product in produts  %}
			<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 px-1">
					{% if product.image %}
					<img class="img-fluid" src="{{product.imageURL}}">
				{% endif %}
				<div class="box-element product">
					<h5>{{product.name}}</h5>
					<h6 style="display:inline-block;">Rp. {{product.price|floatformat:3}}</h6>
					<hr>
					<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">+ Keranjang</button>
					<a class="btn btn-outline-success" href="">Lihat</a>
				</div>
				<br>
				
			</div>
		{% endfor %}
	</div>
{% endblock content %}

shop/templates/shop/product_detail.html
{% extends "shop/main.html" %}
{% load static %}

{% block page_title %}
	{{product.name}}
{% endblock page_title %}

{% block content %}
	<div class="row">
		<div class="col">
				
					
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			  <ol class="carousel-indicators">
			    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			  </ol>
			  <div class="carousel-inner">
			    <div class="carousel-item active">
			      {% if product.image %}
					<center><img class="img-fluid" src="{{product.imageURL}}"></center>	
				{% endif %}
			    </div>
			    <div class="carousel-item">
			     {% if product.image2 %}
						<center><img class="img-fluid" src="{{product.image2URL}}" ></center>
				{% endif %}
			    </div>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
			<br>
		</div>
	</div>
	<hr>
	<div class="row">	
		<div class="col-9">
			<h4>{{product.name}}</h4>
			<h6>Rp. {{product.price|floatformat:3}}</h6><br>
		</div>
		<div class="col-3">
			<h5 id="left"><button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">+Keranjang</button></h5>
		</div>
	</div>
	
	
	<div class="row">
		<div class="col">
			<div class="box-element2 product">
				<center><h5>Produk yang kami kirim telah lulus quality control</h5></center>
			</div>
		</div>
	</div><br>
	<div class="row">
		<div class="col">
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>
	</div>
{% endblock content %}

shop/templates/shop/store.html
{% extends "shop/main.html" %}
{% load static %}
{% block page_title %}
	Astaraya
{% endblock page_title %}
{% block content %}

<h2></h2><br><br>
	<div class="row">
		{% for product in products  %}
			<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 px-1">
				{% if product.image %}
					<img class="img-fluid" src="{{product.imageURL}}">
				{% endif %}
				<div class="box-element product">
					<h5>{{product.name}}</h5>
					<h6 style="display:inline-block;">Rp. {{product.price|floatformat:3}}</h6>
					<hr>
					<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Keranjang</button>
					<a class="btn btn-outline-success" href="{% url 'store:detail' product.slug %}">Lihat</a>
				</div>
				<br>
				
			</div>
		{% endfor %}
	</div>
	
{% if is_paginated %}
<nav aria-label="storelist">
	<ul class="pagination">	
		{% if page_obj.has_previous %}
			<li class="page-item">
		    	<a class="page-link" href="{% url 'store:perempuan' page_obj.previous_page_number %}">Sebelumnya</a>
			</li>
		{% else %}
			<li class="page-item disabled">
	    		<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Sebelumnya</a>
		{% endif %}

		 {% for page in paginator.page_range %}

		    	{% if page is page_obj.number %}
		    	
		    	 <li class="page-item active" aria-current="page">
		    	 	<span class="page-link" href="#">{{page}} <span class="sr-only">(current)</span></span>
		    	 </li>	
		    	
		    	{% else %}
		    	 <li class="page-item">
		    	 	<a class="page-link" href="{% url 'store:perempuan' page%}">{{page}} </a>
		    	 </li>
		    	{% endif %}
		    {% endfor %}

		{% if page_obj.has_next %}
			<li class="page-item">
		    	<a class="page-link" href="{% url 'store:perempuan' page_obj.next_page_number %}">Berikutnya</a>
			</li>
		{% else %}
			<li class="page-item disabled">
	    		<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Berikutnya</a>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock content %}